quarkus:
  banner:
    enabled: false
  datasource:
    db-kind: postgresql
    username: postgres
    password: pass123
    jdbc.url: jdbc:postgresql://localhost:5432/postgres
    
  hibernate-orm:
    database:
      generation: none

  swagger-ui:
    always-include: true
    operations-sorter: method
  smallrye-openapi:
    info-title: Educoach API
    info-version: 1.0.0
  http:
    port: 3000
  rest-client:
    chatgpt:
      url: https://api.openai.com
openai:
  key: ${OPENAI_KEY}
  model: gpt-4o-mini