create table teachers
(
    id            bigserial primary key,
    first_name    text not null,
    last_name     text not null,
    creation_date timestamp(6) default now()
);

alter sequence teachers_id_seq RESTART 1000;

create table lessons (
        id bigint generated by default as identity,
        name varchar(255),
        subject_id bigint,
        teacher_id bigint,
        topic_id bigint,
        primary key (id)
    );

    create table subjects (
        id bigint generated by default as identity,
        color varchar(255),
        designation varchar(255),
        primary key (id)
    );

    alter table if exists teachers 
       alter column first_name set data type varchar(255);

    alter table if exists teachers 
       alter column last_name set data type varchar(255);

    create table topics (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    alter table if exists lessons 
       add constraint FKe94a0k21xpi7glv89af90lwjv 
       foreign key (subject_id) 
       references subjects;

    alter table if exists lessons 
       add constraint FKbr76cuebuufbbltujpfq04tto 
       foreign key (teacher_id) 
       references teachers;

    alter table if exists lessons 
       add constraint FKn1lqfilldva7f2y31fxf3p4p1 
       foreign key (topic_id) 
       references topics;